CREATE OR REPLACE VIEW "REPORT_74" AS
SELECT
  sq.monat,
  sq.umsatz,
  SUM(sq.umsatz) OVER(ORDER BY sq.monat ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS "LAUFENDE_SUMME",
  AVG(sq.umsatz) OVER(ORDER BY sq.monat ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) AS "AVG"
FROM (
  SELECT
    TO_CHAR(o.order_date, 'YYYY-MM') AS "MONAT",
    SUM(o.order_total) AS "UMSATZ"
  FROM orders o
  WHERE EXTRACT(YEAR FROM o.order_date) = '2007'
  GROUP BY TO_CHAR(o.order_date, 'YYYY-MM')
) sq;
