CREATE SEQUENZ "SEQ_TIERNR"
  START WITH 10
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE OR REPLACE TRIGGER "TIERE_I"
BEFORE INSERT OR UPDATE ON TIERE
FOR EACH ROW
DECLARE

BEGIN
  IF UPDATING('Tiernr') THEN
    RAISE_APPLICATION_ERROR(-20001, 'Tiernr darf nicht verändert werden!');
  END IF;

  IF INSERTING THEN
    :NEW.Tiernr := :SEQ_TIERNR.NEXTVAL;
  END IF;
END;
/