CREATE TABLE Adressen (
  Adressnr NUMBER(38) NOT NULL,
  Strasse VARCHAR2(50) NOT NULL,
  Hausnr VARCHAR2(8) NOT NULL,
  Ortnr NUMBER(8),
  CONSTRAINT "PK_ADRESSNR" PRIMARY KEY (Adressnr)
);

CREATE TABLE Orte (
  Ortnr NUMBER(8) NOT NULL,
  PLZ VARCHAR2(5) NOT NULL,
  Ort VARCHAR2(50) NOT NULL,
  CONSTRAINT "PK_ORTNR" PRIMARY KEY (Ortnr)
);