DROP TABLE "TDWH_09_01" CASCADE CONSTRAINTS PURGE;

CREATE TABLE "TDWH_09_01" (
  "ORDER_ID" NUMBER(8),
  "ORDER_DATE" DATE,
  "CHANNEL_ID" NUMBER(8),
  "CUSTOMER_ID" NUMBER(8),
  "ORDER_STATUS" NUMBER(2),
  "SALES_REP_ID" NUMBER(4),
  "PRODUCT_ID" NUMBER(4),
  "LINE_ITEM_ID" NUMBER(2),
  "QUANTITY" NUMBER(3)
)
ORGANIZATION EXTERNAL(
  DEFAULT DIRECTORY "STUDENT_DIR"
  ACCESS PARAMETERS(
    RECORDS DELIMITED BY NEWLINE
    NOBADFILE
    NOLOGFILE
    NODISCARDFILE
    FIELDS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"'
    MISSING FIELD VALUES ARE NULL
    (
      "ORDER_ID",
      "ORDER_DATE" DATE 'DD.MM.YYYY HH24:MI:SS',
      "CHANNEL_ID",
      "CUSTOMER_ID",
      "ORDER_STATUS",
      "SALES_REP_ID",
      "PRODUCT_ID",
      "LINE_ITEM_ID",
      "QUANTITY"

    )
  )
  LOCATION('orders.csv')
)
REJECT LIMIT UNLIMITED;