DROP TABLE "REPORT_93";

CREATE TABLE "REPORT_93" (
  order_id NUMBER(8),
  order_date DATE,
  order_status NUMBER(2)
)
ORGANIZATION EXTERNAL(
  DEFAULT DIRECTORY "STUDENT_DIR"
  ACCESS PARAMETERS(
    RECORDS DELIMITED BY NEWLINE
    NOBADFILE
    NOLOGFILE
    NODISCARDFILE
    FIELDS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"'
    MISSING FIELD VALUES ARE NULL
    (
      order_id,
      order_date DATE 'DD.MM.YYYY HH24:MI:SS',
      order_status
    )
  )
  LOCATION('orders.csv')
)
REJECT LIMIT UNLIMITED;

SELECT *
FROM report_93;