DROP TABLE "TDWH_09_03";

CREATE TABLE "TDWH_09_03" (
  "ORDER_ID" NUMBER(8),
  "ORDER_DATE" DATE,
  "ORDER_STATUS" NUMBER(2)
)
ORGANIZATION EXTERNAL(
  DEFAULT DIRECTORY "STUDENT_DIR"
  ACCESS PARAMETERS(
    RECORDS DELIMITED BY NEWLINE
    NOBADFILE
    NOLOGFILE
    NODISCARDFILE
    FIELDS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"'
    MISSING FIELD VALUES ARE NULL
    (
      "ORDER_ID",
      "ORDER_DATE" DATE 'DD.MM.YYYY HH24:MI:SS',
      "ORDER_STATUS"
    )
  )
  LOCATION('orders.csv')
)
REJECT LIMIT UNLIMITED;